MarkomApplication/_01.MarkomApplication.Web/Controllers/TSouvenirController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _02.MarkomApplication.ModelAccess;
using _03.MarkomApplication.ModelView;
using _04.MarkomApplication.ModelData;

namespace _01.MarkomApplication.Web.Controllers
{
    public class TSouvenirController : Controller
    {
        // GET: TSouvenir
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string searchCode, string SearchReceived, DateTime? searchReceivedDate, DateTime? searchCreatedDate, string searchCreated)
        {
            List<TSouvenirModelView> List = new List<TSouvenirModelView>();
            List = TSouvenirModelAccess.GetListAll(searchCode, SearchReceived, searchReceivedDate, searchCreatedDate, searchCreated);
            ViewBag.DataKosong = TSouvenirModelAccess.DataKosong;
            return PartialView("List", List);
        }

        public ActionResult Create()
        {
            ViewBag.receivedName = new SelectList(TSouvenirModelAccess.receivedName(), "id", "fullName");
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(TSouvenirModelView paramModel)
        {
            try
            {
                TSouvenirModelAccess.Message = string.Empty;

                paramModel.createdBy = 1;
                paramModel.createdDate = DateTime.Now;
                paramModel.isDelete = false;

                if (null == paramModel.receivedBy || null == paramModel.receivedDate)
                {
                    TSouvenirModelAccess.Message = "Anda belum memasukan semua data. Silahkan ulangi kembali";
                }

                if (string.IsNullOrEmpty(TSouvenirModelAccess.Message))
                {
                    //Create auto generate transaction stock code
                    using (var db = new Db_MarkomEntities())
                    {
                        string codeDate = paramModel.receivedDate.Value.ToString("ddMMyy");
                        string nol = "";
                        t_souvenir cek = db.t_souvenir.OrderByDescending(x => x.code).First();
                        int simpan = int.Parse(cek.code.Substring(10));
                        simpan++;
                        for (int i = simpan.ToString().Length; i < 5; i++)
                        {
                            nol = nol + "0";
                        }
                        paramModel.code = "TRSV" + codeDate + nol + simpan;
                    }

                    return Json(new
                    {
                        success = TSouvenirModelAccess.Insert(paramModel),
                        message = paramModel.code
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = TSouvenirModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }
































    }
}

MarkomApplication/_01.MarkomApplication.Web/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _02.MarkomApplication.ModelAccess;
using _03.MarkomApplication.ModelView;
using _04.MarkomApplication.ModelData;

namespace _01.MarkomApplication.Web.Controllers
{
    public class UnitController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string searchName, string searchCode, DateTime? searchDate, string searchCreatedUnit)
        {
            List<UnitModelView> List = new List<UnitModelView>();
            List = UnitModelAccess.GetListAll(searchName, searchCode, searchDate, searchCreatedUnit);
            ViewBag.UnitCode = new SelectList(List, "code", "code");
            ViewBag.UnitName = new SelectList(List, "name", "name");
            ViewBag.DataKosong = UnitModelAccess.DataKosong;
            return PartialView("List", List);
        }

        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(UnitModelView paramModel)
        {
            try
            {
                UnitModelAccess.Message = string.Empty;

                //Create auto generate unit_code
                using (var db = new Db_MarkomEntities())
                {
                    string nol = "";
                    m_unit cek = db.m_unit.OrderByDescending(x => x.code).First();
                    int simpan = int.Parse(cek.code.Substring(3));
                    simpan++;
                    for (int i = simpan.ToString().Length; i < 4; i++)
                    {
                        nol = nol + "0";
                    }
                    paramModel.code = "UN" + nol + simpan;
                }

                paramModel.createdBy = "Administrator";
                paramModel.createdDate = DateTime.Now;
                paramModel.isDelete = false;

                if (null == paramModel.name)
                {
                    UnitModelAccess.Message = "Anda belum memasukan semua data. Silahkan ulangi kembali";
                }
                if (string.IsNullOrEmpty(UnitModelAccess.Message))
                {
                    return Json(new
                    {
                        success = UnitModelAccess.Insert(paramModel),
                        message = paramModel.code
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = UnitModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(Int32 paramId)
        {
            return PartialView(UnitModelAccess.GetDetailById(paramId));
        }

        [HttpPost]
        public ActionResult Edit(UnitModelView paramModel)
        {
            try
            {
                UnitModelAccess.Message = string.Empty;

                paramModel.updatedBy = "Zoni";
                paramModel.updatedDate = DateTime.Now;

                if (null == paramModel.name)
                {
                    UnitModelAccess.Message = "Anda belum memasukan semua data. Silahkan ulangi kembali";
                }
                if (string.IsNullOrEmpty(UnitModelAccess.Message))
                {
                    return Json(new
                    {
                        success = UnitModelAccess.Update(paramModel),
                        message = UnitModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = UnitModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Detail(Int32 paramId)
        {
            return PartialView(UnitModelAccess.GetDetailById(paramId));
        }

        public ActionResult Delete(Int32 paramId)
        {
            return PartialView(UnitModelAccess.GetDetailById(paramId));
        }

        [HttpPost]
        public ActionResult Delete(UnitModelView paramModel)
        {
            try
            {
                return Json(new
                {
                    success = UnitModelAccess.Delete(paramModel),
                    message = UnitModelAccess.Message
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }





    }
}

MarkomApplication/_01.MarkomApplication.Web/Views/TSouvenir/Create.cshtml
@model _03.MarkomApplication.ModelView.TSouvenirModelView

@{
    ViewBag.Title = "Create";
    int itemRow = 1;
}

<form style="color:#343a40; border:1px solid #d5d5d5">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <label style="float:right">*Transaction Code</label>
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label style="float:right">*Received By</label>
            </div>
            <div class="col-md-5">
                @Html.DropDownListFor(model => model.receivedBy, (IEnumerable<SelectListItem>)ViewBag.receivedName, "-Select Employee-", new { @class = "form-control" })
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label style="float:right">*Received Date</label>
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.receivedDate, new { htmlAttributes = new { @class = "form-control", onfocus = "this.type='date'", placeholder = "Select Date" } })
                <span class="validasiAlert validasi3" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label style="float:right">Note</label>
            </div>
            <div class="col-md-5">
                @Html.TextAreaFor(model => model.note, htmlAttributes: new { @class = "form-control textareaz", @placeholder = "Type Note" })
            </div>
        </div>
    </div>
</form>

<form style="color:#343a40; padding-top:15px">
    <div class="modal-body" style="border:1px solid #d5d5d5">
        <div class="row" style="width:100px">
            <button type="button" class="btn btn-block btn-primary" id="add_item">Add Item</button>
        </div>
        <div class="row" style="padding-top:15px">
            <label class="col-md-4">Souvenir Name</label>
            <label class="col-md-2">Qty</label>
            <label class="col-md-4">Note</label>
        </div>
        @{
            var i = 0;
            while (i < itemRow)
            {
                i += 1;
                <div class="row" style="padding-top:10px">
                    <div class="col-md-4" id='"S_Name_"+@i' style="padding-right:5px">
                        <input class="form-control" style="width:100%" />
                    </div>
                    <div class="col-md-2" style="padding-right:5px">
                        <input class="form-control" />
                    </div>
                    <div class="col-md-4" style="padding-right:20px">
                        <input class="form-control" />
                    </div>
                    <div style="padding-right:5px">
                        <a href="#" id="edit_souvenir"><span class="fas fa-edit"></span></a>
                    </div>
                    <div>
                        <a href="#" id="delete_souvenir"><span class="fas fa-trash"></span></a>
                    </div>
                </div>

            }
        }



    </div>
</form>

<div class="row" style="padding-top:25px">
    <div class="col-md-12">
        <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-block btn-primary" id="add_tsouvenir_save" style="width:80px; float:right; margin-top:0%; margin-right:5px">Save</button>
    </div>
</div>


<script>

    $(document).on("click", "#add_item", function () {
        $.ajax({
            url: '@Url.Action("List", "TSouvenir")',
            type: 'get',
            data: {
                searchCode: vjs_search_tcode,
                SearchReceived: vjs_search_received,
                searchReceivedDate: vjs_search_received_date,
                searchCreatedDate: vjs_search_created_date,
                searchCreated: vjs_search_created
            },
            success: function (result) {
                $("#table-list-tsouvenir").html(result);
            }
        });
    });

</script>

MarkomApplication/_01.MarkomApplication.Web/Views/TSouvenir/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">List Souvenir Stock</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="row" style="padding-bottom:10px">
                            <div class="col-md-9">
                                <div class="alert col-md-8" style="background-color:#cdeaff; color:#007bff; font-weight:bold; margin-bottom:0%; max-width:100%">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <button type="button" class="btn btn-block btn-primary" id="add_tsouvenir" style="width:100px; float:right">Add</button>
                            </div>
                        </div>
                        <div id="table-list-tsouvenir"></div> <!-- Tempat List -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- modal popup bootstrap - CRUD Form -->
<div class="modal fade" id="modal-form-tsouvenir">
    <div class="modal-dialog" role="document" style="width:700px; max-width:100%">
        <!-- modal content -->
        <div class="modal-content" style=" border-color:#007bff">
            <!-- modal header -->
            <div class="modal-header" id="modal-header" style="background-color:#007bff; color:white; font-size:larger">
            </div>
            <!-- modal body dan footer -->
            <div class="div-bind-form" id="div-bind-form" style="margin-top: 15px; margin-left: 15px; margin-right: 15px; margin-bottom: 15px">
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
</div>


<!-- modal popup delete -->
<div class="modal fade" id="modal-form-tsouvenir-delete">
    <div class="modal-dialog" role="document" style="width:230px; max-width:100%">
        <div class="modal-content" style=" border-color:gainsboro">
            <div class="modal-header" style="background-color:gainsboro">
                <div class="modal-title" id="modal-header-delete" style="margin:auto; font-size:large">
                    Judul Modal
                </div>
            </div>
            <div class="div-bind-form" id="div-bind-form" style=" margin-left: 5px; margin-right: 5px; margin-bottom: 5px">
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts{
    <script type="text/javascript">
        var vjs_loading = '<div class="progress progress-striped active" style="margin-bottom:0"> <div class="progress-bar" style="width:100%"> </div> </div>';

        $(document).ready(function () {
            ShowList();
            $(".alert").hide();
        });

        //Variable seacrh
        var vjs_search_tcode = '';
        var vjs_search_received = '';
        let vjs_search_received_date = '';
        let vjs_search_created_date = '';
        var vjs_search_created = '';

        function ShowList() {
            $.ajax({
                url: '@Url.Action("List", "TSouvenir")',
                type: 'get',
                data: {
                    searchCode: vjs_search_tcode,
                    SearchReceived: vjs_search_received,
                    searchReceivedDate: vjs_search_received_date,
                    searchCreatedDate: vjs_search_created_date,
                    searchCreated: vjs_search_created
                },
                success: function (result) {
                    $("#table-list-tsouvenir").html(result);
                }
            });
        };

        //Search data Tsouvenir
        $(document).on("click", "#search_tsouvenir", function () {
            vjs_search_tcode = $("#search_tcode").val();
            vjs_search_received = $("#search_received").val();
            vjs_search_received_date = $("#search_received_date").val();
            vjs_search_created_date = $("#search_created_date").val();
            vjs_search_created = $("#search_created").val();
            ShowList();
        });


        //Popup Tambah Souvenir stock
        $(document).on("click", "#add_tsouvenir", function () {
            $("#modal-form-tsouvenir").modal("show");
            $("#modal-header").html("Add Souvenir Stock");
            $.ajax({
                url: '@Url.Action("Create", "TSouvenir")',
                type: 'get',
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Save Add data Souvenir stock
        $(document).on("click", "#add_tsouvenir_save", function () {
            var vjs_received = $("#receivedBy").val();
            vjs_received == "" ? $(".validasi2").show() : $(".validasi2").hide();
            var vjs_received_date = $("#receivedDate").val();
            vjs_received_date == "" ? $(".validasi3").show() : $(".validasi3").hide();
            var vjs_note = $("#note").val();

            var item = {
                receivedBy: vjs_received,
                receivedDate: vjs_received_date,
                note: vjs_note
            };
            $.ajax({
                url: '@Url.Action("Create", "TSouvenir")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-tsouvenir").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Saved! New role has been add with code " + result.message + " !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });


        //Popup edit Unit
        $(document).on("click", "#edit_unit", function () {
            var vjs_id = $(this).attr("data-id");
            var vjs_name_popup = $(this).attr("data-name");
            var vjs_code_popup = $(this).attr("data-code");
            $("#modal-form-unit").modal("show");
            $("#modal-header").html("Edit Unit - "+vjs_name_popup+" ("+vjs_code_popup+")");

            $.ajax({
                url: '@Url.Action("Edit", "Unit")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Save Edit data Unit
        $(document).on("click", "#edit_unit_save", function () {
            var vjs_id = $("#id").val();
            var vjs_name = $("#name").val();
            vjs_name == "" ? $(".validasi2").show() : $(".validasi2").hide();
            var vjs_description = $("#description").val();

            var item = {
                id: vjs_id,
                name: vjs_name,
                description: vjs_description
            };
            $.ajax({
                url: '@Url.Action("Edit", "Unit")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-unit").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Updated! Data unit has been updated !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });


        //Popup detail/view Unit
        $(document).on("click", "#detail_unit", function () {
            var vjs_id = $(this).attr("data-id");
            var vjs_name_popup = $(this).attr("data-name");
            var vjs_code_popup = $(this).attr("data-code");
            $("#modal-form-unit").modal("show");
            $("#modal-header").html("View Unit - "+vjs_name_popup+" ("+vjs_code_popup+")");

            $.ajax({
                url: '@Url.Action("Detail", "Unit")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Popup delete Unit
        $(document).on("click", "#delete_unit", function () {
            var vjs_id = $(this).attr("data-id");
            $("#modal-form-unit-delete").modal("show");
            $("#modal-header-delete").html("Delete Data ?");

            $.ajax({
                url: '@Url.Action("Delete", "Unit")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                }
            });
        });

        //Save delete data Unit
        $(document).on("click", "#delete_unit_save", function () {
            var vjs_id = $("#id").val();
            var vjs_code = $("#code").val();
            var item = {
                id: vjs_id,
                code: vjs_code
            };
            $.ajax({
                url: '@Url.Action("Delete", "Unit")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-unit-delete").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Deleted! Data unit with code "+vjs_code+" has been deleted !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });





    </script>
}

MarkomApplication/_01.MarkomApplication.Web/Views/TSouvenir/List.cshtml
@model IEnumerable<_03.MarkomApplication.ModelView.TSouvenirModelView>

@{
    ViewBag.Title = "List";
    int no = 1;
}

    <div class="row" style="width:100%; margin-left:0%; padding-bottom:10px">
        <input class="form-control col-xl-2" id="search_tcode" placeholder="Transaction Code" style="margin:auto" />
        <input class="form-control col-xl-2" id="search_received" placeholder="Received By" style="margin:auto" />
        <input class="form-control col-xl-2" id="search_received_date" placeholder="Received Date" onfocus="this.type='date'" style="margin:auto" />
        <input class="form-control col-xl-2" id="search_created_date" placeholder="Created" onfocus="this.type='date'" style="margin:auto" />
        <input class="form-control col-xl-2" id="search_created" placeholder="Created By" style="margin:auto" />
        <button type="button" class="btn btn-block bg-gradient-warning" style="width:100px; float:right" id="search_tsouvenir">Search</button>
    </div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>No</th>
            <th>Transaction Code</th>
            <th>Received By</th>
            <th>Received Date</th>
            <th>Created Date</th>
            <th>Created By</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @no
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.received)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tanggalReceived)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tanggalCreated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created)
                </td>
                <td>
                    <a href="#" id="detail_tsouvenir" data-code="@item.code" data-id="@item.id"><span class="fas fa-search"></span></a>
                    <a href="#" id="edit_tsouvenir" data-code="@item.code" data-id="@item.id"><span class="fas fa-edit"></span></a>
                </td>
            </tr>
            no++;
        }
    </tbody>
</table>
<div style="text-align: center; font-size: large; color: #007bff">@ViewBag.DataKosong</div>